---
title: "Block Estimation for Univariate Data"
author: "Andrea Ferrero"
date: "2025-11-18"
output: html_document
---

## 1. Idea and Motivation

In the context of our model, we are considering $X_1, \dots, X_n \sim F$, where $F(x_1, \dots, x_n) = C_{n, \theta}(F(x_1), \dots, F(x_n))$. This means we are considering the sample $U_1, \dots, U_n$ as one realisation of the copula in $[0,1]^n$, which combined with the (unknown) margin $F$ yields the original sample.

In principle, this means we would have to estimate the copula parameter from just one realisation. Therefore, we need to think of a structure that would allow us to learn more from a single dataset.

The idea is to assume we can break the sequence in $K$ blocks, each of which contains $n_k$ observations (we assume blocks of the same size for simplicity, $n_k = m$). As a starting point, consider blocks to be independent of one another, but observations within blocks are dependent and modelled through a unique copula:

\[
(U_{1,k}, \dots, U_{m, k})_{k = 1, \dots, K} \sim C_\theta
\]

This gives us the opportunity to learn about the unique copula parameter treating each block of $n_k$ observations as independent realisations from the copula model.

## 2. Estimation

A review on estimation methods for Archimedean copulas in high dimension is given by Hofert et al. (2013), where they find maximum likelihood to be the one performing the best, both under known and unknown margins, despite the gain in precision compared to other methods in the latter case is not so obvious.

However, the experiments show that if you were to consider blocks of hundreds of observations (from $n_k > 220$), computation of the copula density would be unfeasible and as a consequence MLE cannot be performed. Diagonal MLE can be an alternative as it scales well with dimensions, despite taking information from the data only via the copula diagonal.

See notes on Diagonal Estimation for details on frequentist and bayesian estimation.

