---
title: "Extreme Copula-Based Markov Models: A Research Proposal"
output: pdf_document
---

## 1. Introduction: Copula-Based Markov Models

Copulas have been successfully employed to model univariate time series by constructing Markov processes with flexible dependence structures. A Copula-Based Markov Model (CMM) of order one is defined by the relation:

\[ 
(Y_t, Y_{t+1}) \sim C(F(y_t), F(y_{t+1})) 
\]

with $F$ the invariant marginal distribution. This approach differs from defining a copula over the entire sequence $Y_1, \dots , Y_n$ and offers the computational advantage of using bivariate copulas, characterised by a likelihood simpler to evaluate.

Chen et al. (2009) study semiparametric estimation of this model in the frequentist framework, while investigating mixing properties of the model using tail-dependent copulas (Clayton, Gumbel,...), extending existing results. In particular, CMMs are geometrically ergodic, hence geometrically $\beta$-mixing, under certain conditions which are usually satisfied by common copula choices. This means realisations from CMMs with Clayton or Gumbel, despite looking persistent, are actually weakly dependent and "short memory". Semiparametric estimation is carried out with sieve maximum likelihood, and found to be superior to the classic Inference From Margin method in terms of efficiency and bias.

## 2. Connection to EVT

Connecting CMM to the theory of Extremes, we know from the mixing properties that the limit distribution of the (adequately) normalised maximum will be:

\[
P\left( \frac{M_n - b_n}{a_n} < z \right) \to G(z) = H^\theta(z)
\]

with $H$ the GEV limit distribution of the maximum under iid sampling from F, and $\theta \in (0,1]$ the extremal index.

## 3. EVT and Markov Chains

Work has been carried out on the link between Markov Chains and Extremes. In particular, Smith (1992), Perfekt (1994) and Yun (1998) derive the extremal index for Markov Processes, showing how it is related to the Extremal Chain.

## 4. Idea

Leverage results on the extremal index of Markov Chains to study the maxima under CMM. Potentially, a Bayesian approach could be performed to quantify uncertainty on $\theta$.